# Generated by Django 4.1.2 on 2022-10-27 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
    ]
